/**
 * SEO OS++ Phase 0 Current State Analysis Writer
 * 
 * Writes analysis artifacts: analysis.json, analysis.md, analysis-summary.md
 */

import { AnalysisResult, Finding, AnalysisScores } from "./types";
import { getScoreGrade } from "./scorer";

// ═══════════════════════════════════════════════════════════════
// MARKDOWN GENERATORS
// ═══════════════════════════════════════════════════════════════

function severityEmoji(severity: string): string {
    switch (severity) {
        case "critical": return "🔴";
        case "high": return "🟠";
        case "medium": return "🟡";
        case "low": return "🟢";
        default: return "⚪";
    }
}

function generateFindingSection(finding: Finding): string {
    let md = `### ${severityEmoji(finding.severity)} ${finding.title}\n\n`;
    md += `**Severity**: ${finding.severity.toUpperCase()} | **Category**: ${finding.category} | **ID**: ${finding.id}\n\n`;
    md += `${finding.description}\n\n`;

    if (finding.evidence.length > 0) {
        md += `**Evidence**:\n`;
        finding.evidence.forEach(e => {
            md += `- ${e.url}`;
            if (e.snippet) md += ` — \`${e.snippet}\``;
            if (e.metric) md += ` — ${e.metric}`;
            md += `\n`;
        });
        md += `\n`;
    }

    md += `**Recommendation**: ${finding.recommendation}\n\n`;
    md += `**SEO OS Module**: ${finding.seoOsModule} | **Impact**: ${finding.impactEstimate}\n\n`;
    md += `---\n\n`;

    return md;
}

function generateScoreSection(scores: AnalysisScores): string {
    let md = `## Current State Analysis Scores\n\n`;
    md += `| Category | Score | Grade |\n`;
    md += `|----------|-------|-------|\n`;
    md += `| Technical | ${scores.categories.technical} | ${getScoreGrade(scores.categories.technical)} |\n`;
    md += `| On-Page | ${scores.categories.onpage} | ${getScoreGrade(scores.categories.onpage)} |\n`;
    md += `| Local | ${scores.categories.local} | ${getScoreGrade(scores.categories.local)} |\n`;
    md += `| AEO | ${scores.categories.aeo} | ${getScoreGrade(scores.categories.aeo)} |\n`;
    md += `| **Overall** | **${scores.overall}** | **${getScoreGrade(scores.overall)}** |\n\n`;

    md += `*Weights: Technical ${scores.weights.technical * 100}%, On-Page ${scores.weights.onpage * 100}%, Local ${scores.weights.local * 100}%, AEO ${scores.weights.aeo * 100}%*\n\n`;

    return md;
}

// ═══════════════════════════════════════════════════════════════
// FULL ANALYSIS REPORT
// ═══════════════════════════════════════════════════════════════

export function generateAnalysisMarkdown(result: AnalysisResult): string {
    let md = `# Current State Analysis Report: ${result.metadata.businessName}\n\n`;
    md += `**Target URL**: ${result.metadata.targetUrl}\n`;
    md += `**Analysis Date**: ${result.metadata.analyzedAt}\n`;
    md += `**Pages Crawled**: ${result.metadata.pagesCrawled} of ${result.metadata.pagesAttempted} attempted\n`;
    md += `**Crawl Status**: ${result.metadata.crawlStatus}\n\n`;

    md += `---\n\n`;

    // Scores
    md += generateScoreSection(result.scores);

    md += `---\n\n`;

    // Top Blockers
    md += `## Top Blockers\n\n`;
    if (result.topBlockers.length === 0) {
        md += `No critical issues found.\n\n`;
    } else {
        result.topBlockers.forEach(f => {
            md += generateFindingSection(f);
        });
    }

    // All Findings by Category
    const categories = ["technical", "onpage", "local", "aeo"] as const;
    for (const cat of categories) {
        const catFindings = result.findings.filter(f => f.category === cat);
        if (catFindings.length > 0) {
            md += `## ${cat.charAt(0).toUpperCase() + cat.slice(1)} Issues\n\n`;
            catFindings.forEach(f => {
                md += generateFindingSection(f);
            });
        }
    }

    // Pages Crawled Summary
    md += `## Pages Crawled\n\n`;
    md += `| URL | Status | Title | Words |\n`;
    md += `|-----|--------|-------|-------|\n`;
    result.pages.slice(0, 20).forEach(p => {
        const title = p.title ? p.title.substring(0, 40) + (p.title.length > 40 ? "..." : "") : "(none)";
        md += `| ${p.url.substring(0, 50)}... | ${p.status} | ${title} | ${p.wordCount} |\n`;
    });
    if (result.pages.length > 20) {
        md += `\n*...and ${result.pages.length - 20} more pages*\n`;
    }

    md += `\n---\n\n*Generated by SEO OS++ Phase 0 Current State Analysis*\n`;

    return md;
}

// ═══════════════════════════════════════════════════════════════
// ANALYSIS SUMMARY (1-PAGER)
// ═══════════════════════════════════════════════════════════════

export function generateAnalysisSummary(result: AnalysisResult): string {
    let md = `# Current State Analysis Summary: ${result.metadata.businessName}\n\n`;

    // Overall Score Box
    md += `## Overall Score: ${result.scores.overall}/100 (${getScoreGrade(result.scores.overall)})\n\n`;

    // Category Scores
    md += `| Technical | On-Page | Local | AEO |\n`;
    md += `|:---------:|:-------:|:-----:|:---:|\n`;
    md += `| ${result.scores.categories.technical} | ${result.scores.categories.onpage} | ${result.scores.categories.local} | ${result.scores.categories.aeo} |\n\n`;

    // Top 5 Issues
    md += `## Top 5 Issues to Fix\n\n`;
    result.topBlockers.slice(0, 5).forEach((f, i) => {
        md += `${i + 1}. ${severityEmoji(f.severity)} **${f.title}** — ${f.description.split('.')[0]}.\n`;
    });
    md += `\n`;

    // Quick Wins
    md += `## Quick Wins\n\n`;
    const quickWins = result.findings.filter(f =>
        f.severity === "low" || f.severity === "medium"
    ).slice(0, 3);
    quickWins.forEach((f, i) => {
        md += `${i + 1}. ${f.title} — ${f.recommendation}\n`;
    });
    md += `\n`;

    // Module Coverage
    md += `## What SEO OS++ Will Fix\n\n`;
    const modules = new Map<string, number>();
    result.findings.forEach(f => {
        modules.set(f.seoOsModule, (modules.get(f.seoOsModule) || 0) + 1);
    });
    modules.forEach((count, module) => {
        md += `- **${module}**: ${count} issue${count > 1 ? 's' : ''}\n`;
    });

    md += `\n---\n\n*${result.metadata.pagesCrawled} pages analyzed on ${result.metadata.analyzedAt.split('T')[0]}*\n`;

    return md;
}

// ═══════════════════════════════════════════════════════════════
// JSON OUTPUT
// ═══════════════════════════════════════════════════════════════

export function generateAnalysisJson(result: AnalysisResult): string {
    return JSON.stringify(result, null, 2);
}

// Backward compatibility exports
export const generateAuditMarkdown = generateAnalysisMarkdown;
export const generateAuditSummary = generateAnalysisSummary;
export const generateAuditJson = generateAnalysisJson;
